### ISSUE TITLE
Cannot install wps-office

### ISSUE THREAD

**Issue by brittyazel** [rmarquis/pacaur#409]
Lately, when trying to install wps-office with pacaur, everything looks like it built successfully, but then I am greeted with this:
:: Installing wps-office package(s)...
:: wps-office package(s) failed to install. Check .SRCINFO for mismatching data with PKGBUILD.

I would like to note that as of today when using pacaur package I did not get the error message, it just silently failed to install, but the pacaur-git package does provide me with the error.
The strange thing is that manually creating the package from the pkgbuild works great, although there is a long pause where the cursor stops blinking once I run the pacman -U command.

I have no idea what to do.

**Comment by rmarquis** [comment]
First, since pacman 5.0.0 just hit [core], ensure your system is up-to-date and that expac 5 (also from [core]) is correctly installed. Then recompile cower manually with makepkg.

Yes, I added this warning message in a latest release - to give a hint about why the install might not happening.

Pacaur, unlike most other helpers, relies on the AUR RPC interface to solve dependencies. To get full accurate information, the .SRCINFO file needs to be accurate, ie. in sync with the PKGBUILD (from which it is generate by the maintainer).

In your case, it doesn't seem this issue is happening. The .SRCINFO [looks correct](https://aur.archlinux.org/cgit/aur.git/log/?h=wps-office), and I did succeed in installing wps-office.

Once you've made the pacman 5.0.0 transition and installed the newest pacaur, can you try again and see if the issue still happen? It the issue still arise, I'll need to have a look at a [debug output](https://github.com/rmarquis/pacaur/wiki/Bug-reports).

**Comment by brittyazel** [comment]
I tried again, doing everything that you said and I get the exact same error. Is there a chance that an old .SRCINFO is stored in my system from a previous build somehow?

Here is that info:

> + version=4.5.0
> + LC_COLLATE=C
> + TEXTDOMAIN=pacaur
> + TEXTDOMAINDIR=/usr/share/locale
> + [[ -n '' ]]
> + configdir=/etc/xdg/pacaur
> + userconfigdir=/home/britt/.config/pacaur
> + userpacmandir=/home/britt/.config/pacman
> + [[ -r '' ]]
> + source /etc/makepkg.conf
> ++ DLAGENTS=('ftp::/usr/bin/curl -fC - --ftp-pasv --retry 3 --retry-delay 3 -o %o %u' 'http::/usr/bin/curl -fLC - --retry 3 --retry-delay 3 -o %o %u' 'https::/usr/bin/curl -fLC - --retry 3 --retry-delay 3 -o %o %u' 'rsync::/usr/bin/rsync --no-motd -z %u %o' 'scp::/usr/bin/scp -C %u %o')
> ++ VCSCLIENTS=('bzr::bzr' 'git::git' 'hg::mercurial' 'svn::subversion')
> ++ CARCH=x86_64
> ++ CHOST=x86_64-unknown-linux-gnu
> ++ CPPFLAGS=-D_FORTIFY_SOURCE=2
> ++ CFLAGS='-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong'
> ++ CXXFLAGS='-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong'
> ++ LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro
> ++ DEBUG_CFLAGS='-g -fvar-tracking-assignments'
> ++ DEBUG_CXXFLAGS='-g -fvar-tracking-assignments'
> ++ BUILDENV=(!distcc color !ccache check !sign)
> ++ OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !optipng !upx !debug)
> ++ INTEGRITY_CHECK=(md5)
> ++ STRIP_BINARIES=--strip-all
> ++ STRIP_SHARED=--strip-unneeded
> ++ STRIP_STATIC=--strip-debug
> ++ MAN_DIRS=({usr{,/local}{,/share},opt/*}/{man,info})
> ++ DOC_DIRS=(usr/{,local/}{,share/}{doc,gtk-doc} opt/*/{doc,gtk-doc})
> ++ PURGE_TARGETS=(usr/{,share}/info/dir .packlist *.pod)
> ++ COMPRESSGZ=(gzip -c -f -n)
> ++ COMPRESSBZ2=(bzip2 -c -f)
> ++ COMPRESSXZ=(xz -c -z -)
> ++ COMPRESSLRZ=(lrzip -q)
> ++ COMPRESSLZO=(lzop -q)
> ++ COMPRESSZ=(compress -c -f)
> ++ PKGEXT=.pkg.tar.xz
> ++ SRCEXT=.src.tar.gz
> + [[ -r /home/britt/.config/pacman/makepkg.conf ]]
> + [[ -r /home/britt/.makepkg.conf ]]
> + tmpdir=/tmp/pacaurtmp-britt
> + clonedir=/tmp/pacaurtmp-britt
> + editor=nano
> + displaybuildfiles=full
> + fallback=true
> + silent=false
> + sortby=popularity
> + sudoloop=false
> + pacmanbin=pacman
> + aururl=aur.archlinux.org
> + aurrpc='/rpc.php?type=multiinfo&v=4'
> + source /etc/xdg/pacaur/config
> + [[ -r /home/britt/.config/pacaur/config ]]
> + [[ ! -d /tmp/pacaurtmp-britt ]]
> + [[ ! -d /tmp/pacaurtmp-britt ]]
> + trap Cancel INT
> + args=($@)
> + count=0
> + [[ -n '' ]]
> ++ grep '^Color' /etc/pacman.conf
> + [[ -n '' ]]
> ++ grep '^Color' /etc/pacman.conf
> + [[ -z '' ]]
> + [[ '' = \a\l\w\a\y\s ]]
> + [[ '' = \a\u\t\o ]]
> + [[ '' != \a\l\w\a\y\s ]]
> + [[ '' != \a\u\t\o ]]
> + makeopts+=("--nocolor")
> + pacmanarg=(${pacmanarg[@]/--/})
> + pacmanarg=(${pacmanarg[@]/-r/})
> + pacmanarg=(${pacmanarg[@]/-a/})
> + [[ '' = sync ]]
> + [[ -n '' ]]
> + [[ -n '' ]]
> + [[ -n '' ]]
> + [[ ! -n nano ]]
> + [[ '' = sync ]]
> + [[ ! -w /tmp/pacaurtmp-britt ]]
> + [[ -z '' ]]
> + [[ '' = download ]]
> + [[ '' = sync ]]
> + [[ '' = editpkg ]]
> + [[ -n '' ]]
> + case $operation in
> + [[ -z '' ]]
> ++ grep -e '-[F]'
> + [[ -n '' ]]
> + [[ -z '' ]]
> + [[ !    =~  --asdeps  ]]
> + [[ !    =~  --asexp  ]]
> + pacman
> error: no operation specified (use -h for help)
> + exit

**Comment by rmarquis** [comment]
Sorry, could you try again to run the debug output: `bash -x pacaur <your command>`.
For some reason, the `<your command>` part got eaten by github and wasn't showing on the debug instructions page... 

It's unlikely that an old .SRCINFO file would stay on the system... or maybe the old one couldn't be removed because of weird permission issue? Check your clone directory and remove any wps-office directory/file if needed (default is `/tmp/pacaur-USER`).

**Comment by brittyazel** [comment]
Same error. Here is the debug output:
http://pastebin.com/en87UjPb

**Comment by rmarquis** [comment]
Oh man, this is weird. The package is correctly created, but pacaur can't find it in the built directory and thus can't install it.

On your machine, pacaur looks for the package in `/tmp/pacaurtmp-britt/wps-office/`, with the file name matching `wps-office-10.1.0.5460_a20p1-1-x86_64.pkg.tar.xz`.

Once the issue occurs, can you look in that directory and see what is the name of the file created?

**Comment by brittyazel** [comment]
wps-office-10.1.0.5460_a20p1-1-x86_64.pkg.tar

This is the output file, and there is no .xz extension

**Comment by rmarquis** [comment]
Thanks, finally found the issue here.

Pacaur takes into account makepkg config settings, and never sources the PKGBUILDs directly. Since the wps-office package redefines the `PKGEXT` extension and overwrites the global value, pacaur fails here. I did miss that when I looked over the PKGBUILD.

The package works fine for me because I did set `PKGEXT` to `pkg.tar` to in my global makepkg.conf (since I don't want/don't need to compress built packages at all).

Since redefining PKGEXT in a PKGBUILD is _somewhat_ correct in PKGBUILD, and done in very big package to reduce installation time, I probably should take care of this in pacaur code itself. I don't want to source the PKGBUILDs directly for security reasons, but I can try to fall back to `pkg.tar` if no built package is found.

Thanks for your time and dedication with this bug. I'll push a fix shortly.

**Comment by brittyazel** [comment]
Than you so much! I'm happy that this turned into something that could potentially help others with their packages. I appreciate your time in helping me with this

**Comment by rmarquis** [comment]
Done in 248ffcfa04176573c8d5b280a0c2456ae4f6b246.

Will be in the next stable release in a few days. Can be used with the _pacaur-git_ package in the meantime.

**Comment by rightaway** [comment]
Has this fix made it into the 'pacaur' AUR package? I'm using 4.5.2-1 but still getting this error when trying to install `openvpn-update-resolv-conf`.

**Comment by rmarquis** [comment]
Yes. You might encounter another issue here. Please open a new ticket with full error message, and with [debut output](https://github.com/rmarquis/pacaur/wiki/Bug-reports) too.

**Comment by brittyazel** [comment]
Weird this issue seems to have returned for me on a different machine. Any changes on your end?

**Comment by rmarquis** [comment]
@brittyazel No, all known issues of that kind that should be fixed in latest release. With which package does the issue occur again? Please provide a new debug output in a new ticket if necessary.
